<a href="https://colab.research.google.com/github/AnalystDhiren/Python-Handson/blob/main/Handson_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
a = [5,7,8,9]
datasets = pd.Series(a)

In [ ]:
print(datasets)

In [ ]:
a = [5,7,8]
datasets = pd.Series(a, index = ["No.1","No.2","No.3"])
print(datasets)

# DATA FRAME

In [ ]:
data = {"Name":["Mr.X","Mr.Y","Miss Z"],"Color":["blue","Yellow","Purple"]}
dataset = pd.DataFrame(data)
print(dataset)

     Name   Color
0    Mr.X    blue
1    Mr.Y  Yellow
2  Miss Z  Purple

# LOADING DATA FROM A FILE

In [ ]:
import pandas as pd

In [ ]:
Data1 = pd.read_csv("C:\\Users\\dhirendra.p_embibe\\Desktop\\data\\Code\\dataset.csv") #inport CSV

In [ ]:
Data1

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
print(Data1.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [ ]:
Data2 = pd.read_excel("C:\\Users\\dhirendra.p_embibe\\Desktop\\data\\Code\\dataset.xlsx") #inport excel

In [ ]:
print(Data2.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [ ]:
#remember for CSV & Text data (pd.read_csv) will be used

In [ ]:
Data3 = pd.read_csv("C:\\Users\\dhirendra.p_embibe\\Desktop\\data\\Code\\dataset.txt") #inport text

In [ ]:
print(Data3.head(5))

  #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
0  1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
1  2\tIvysaur\tGrass\tPoison\t60\t62\t63\t80\t80\...
2  3\tVenusaur\tGrass\tPoison\t80\t82\t83\t100\t1...
3  3\tVenusaurMega Venusaur\tGrass\tPoison\t80\t1...
4  4\tCharmander\tFire\t\t39\t52\t43\t60\t50\t65\...

In [ ]:
print(Data3.describe())

       #\tName\tType 1\tType 2\tHP\tAttack\tDefense\tSp. Atk\tSp. Def\tSpeed\tGeneration\tLegendary
count                                                 800
unique                                                800
top     1\tBulbasaur\tGrass\tPoison\t45\t49\t49\t65\t6...
freq                                                    1

In [ ]:
print(Data2
      .describe()) #data for info

                #          HP      Attack     Defense     Sp. Atk     Sp. Def  \
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000
mean   362.813750   69.258750   79.001250   73.842500   72.820000   71.902500
std    208.343798   25.534669   32.457366   31.183501   32.722294   27.828916
min      1.000000    1.000000    5.000000    5.000000   10.000000   20.000000
25%    184.750000   50.000000   55.000000   50.000000   49.750000   50.000000
50%    364.500000   65.000000   75.000000   70.000000   65.000000   70.000000
75%    539.250000   80.000000  100.000000   90.000000   95.000000   90.000000
max    721.000000  255.000000  190.000000  230.000000  194.000000  230.000000

            Speed  Generation
count  800.000000   800.00000
mean    68.277500     3.32375
std     29.060474     1.66129
min      5.000000     1.00000
25%     45.000000     2.00000
50%     65.000000     3.00000
75%     90.000000     5.00000
max    180.000000     6.00000

In [ ]:
print(Data2.shape)  #count row and columns

(800, 12)

# DATA SLICING

Get title columns

In [ ]:
print(Data2.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
print(Data2["Name"])  #get the data by Gving the NAME

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [ ]:
print(Data2[["Name","Speed"]])  #get the data by Gving the multiple title by NAME

                      Name  Speed
0                Bulbasaur     45
1                  Ivysaur     60
2                 Venusaur     80
3    VenusaurMega Venusaur     80
4               Charmander     65
..                     ...    ...
795                Diancie     50
796    DiancieMega Diancie    110
797    HoopaHoopa Confined     70
798     HoopaHoopa Unbound     80
799              Volcanion     70

[800 rows x 2 columns]

In [ ]:
print(Data2["Name"][0:20]) #get the list fo data with specific count

0                     Bulbasaur
1                       Ivysaur
2                      Venusaur
3         VenusaurMega Venusaur
4                    Charmander
5                    Charmeleon
6                     Charizard
7     CharizardMega Charizard X
8     CharizardMega Charizard Y
9                      Squirtle
10                    Wartortle
11                    Blastoise
12      BlastoiseMega Blastoise
13                     Caterpie
14                      Metapod
15                   Butterfree
16                       Weedle
17                       Kakuna
18                     Beedrill
19        BeedrillMega Beedrill
Name: Name, dtype: object

ILOC - integer Location

In [ ]:
print(Data2.iloc[6])  #get the data Row wise

#                     6
Name          Charizard
Type 1             Fire
Type 2           Flying
HP                   78
Attack               84
Defense              78
Sp. Atk             109
Sp. Def              85
Speed               100
Generation            1
Legendary         False
Name: 6, dtype: object

In [ ]:
print(Data2.iloc[12
                :18])  #get the data Row from A to B wise ## between range

     #                     Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
12   9  BlastoiseMega Blastoise  Water     NaN  79     103      120      135
13  10                 Caterpie    Bug     NaN  45      30       35       20
14  11                  Metapod    Bug     NaN  50      20       55       25
15  12               Butterfree    Bug  Flying  60      45       50       90
16  13                   Weedle    Bug  Poison  40      35       30       20
17  14                   Kakuna    Bug  Poison  45      25       50       25

    Sp. Def  Speed  Generation  Legendary
12      115     78           1      False
13       20     45           1      False
14       25     30           1      False
15       80     70           1      False
16       20     50           1      False
17       25     35           1      False

In [ ]:
print(Data2.iloc[1,2])  #get the data of specific cell (1,2 means 1 row second cell)

Grass

In [ ]:
for index,row in Data2.iterrows():
    print(index,row["Name"])  #get the entire data rowwise w.r.t"Name"

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 Victreebel
78 Tentacool
79 Tentacruel
80 Geodude
81 Graveler
82 Golem
83 Ponyta
84 Rapidash
85 Slowpoke
86 Slowbro
87 SlowbroMega Slowbro
88 Magnemite
89 Magneton
90 Farfetch'd
91 Doduo
92 Dodrio
93 Seel
94 Dewgong
95 Grimer
96 Muk
97 Shellder
98 Cloyster
99 Gastly
100 Haunter
101 Gengar
102 GengarMega Gengar
103 Onix
104 Drowzee
105 Hypno
106 Krabby
107 Kingler
108 Voltorb
109 Electrode
110 Exeggcute
111 Exeggutor
112 Cubone
113 Marowak
114 Hitmonlee
115 Hitmonchan
116 Lickitung
117 Koffing
118 Weezing
119 Rhyhorn
120 Rhydon
121 Chansey
122 Tangela
123 Kangaskhan
124 KangaskhanMega Kangaskhan
125 Horsea
126 Seadra
127 Goldeen
128 Seaking
129 Staryu
130 Starmie
131 Mr. Mime
132 Scyther
133 Jynx
134 Electabuzz
135 Magmar
136 Pinsir
137 PinsirMega Pinsir
138 Tauros
139 Magikarp
140 Gyarados
141 GyaradosMega Gyarados
142 Lapras
143 Ditto
144 Eevee
145 Vaporeon
146 Jolteon
147 Flareon
148 Porygon
149 Omanyte
150 Omastar
151 Kabuto
152 Kabutops
153 Aerodactyl
154 AerodactylMega Aerodactyl
155 Snorlax
156 Articuno
157 Zapdos
158 Moltres
159 Dratini
160 Dragonair
161 Dragonite
162 Mewtwo
163 MewtwoMega Mewtwo X
164 MewtwoMega Mewtwo Y
165 Mew
166 Chikorita
167 Bayleef
168 Meganium
169 Cyndaquil
170 Quilava
171 Typhlosion
172 Totodile
173 Croconaw
174 Feraligatr
175 Sentret
176 Furret
177 Hoothoot
178 Noctowl
179 Ledyba
180 Ledian
181 Spinarak
182 Ariados
183 Crobat
184 Chinchou
185 Lanturn
186 Pichu
187 Cleffa
188 Igglybuff
189 Togepi
190 Togetic
191 Natu
192 Xatu
193 Mareep
194 Flaaffy
195 Ampharos
196 AmpharosMega Ampharos
197 Bellossom
198 Marill
199 Azumarill
200 Sudowoodo
201 Politoed
202 Hoppip
203 Skiploom
204 Jumpluff
205 Aipom
206 Sunkern
207 Sunflora
208 Yanma
209 Wooper
210 Quagsire
211 Espeon
212 Umbreon
213 Murkrow
214 Slowking
215 Misdreavus
216 Unown
217 Wobbuffet
218 Girafarig
219 Pineco
220 Forretress
221 Dunsparce
222 Gligar
223 Steelix
224 SteelixMega Steelix
225 Snubbull
226 Granbull
227 Qwilfish
228 Scizor
229 ScizorMega Scizor
230 Shuckle
231 Heracross
232 HeracrossMega Heracross
233 Sneasel
234 Teddiursa
235 Ursaring
236 Slugma
237 Magcargo
238 Swinub
239 Piloswine
240 Corsola
241 Remoraid
242 Octillery
243 Delibird
244 Mantine
245 Skarmory
246 Houndour
247 Houndoom
248 HoundoomMega Houndoom
249 Kingdra
250 Phanpy
251 Donphan
252 Porygon2
253 Stantler
254 Smeargle
255 Tyrogue
256 Hitmontop
257 Smoochum
258 Elekid
259 Magby
260 Miltank
261 Blissey
262 Raikou
263 Entei
264 Suicune
265 Larvitar
266 Pupitar
267 Tyranitar
268 TyranitarMega Tyranitar
269 Lugia
270 Ho-oh
271 Celebi
272 Treecko
273 Grovyle
274 Sceptile
275 SceptileMega Sceptile
276 Torchic
277 Combusken
278 Blaziken
279 BlazikenMega Blaziken
280 Mudkip
281 Marshtomp
282 Swampert
283 SwampertMega Swampert
284 Poochyena
285 Mightyena
286 Zigzagoon
287 Linoone
288 Wurmple
289 Silcoon
290 Beautifly
291 Cascoon
292 Dustox
293 Lotad
294 Lombre
295 Ludicolo
296 Seedot
297 Nuzleaf
298 Shiftry
299 Taillow
300 Swellow
301 Wingull
302 Pelipper
303 Ralts
304 Kirlia
305 Gardevoir
306 GardevoirMega Gardevoir
307 Surskit
308 Masquerain
309 Shroomish
310 Breloom
311 Slakoth
312 Vigoroth
313 Slaking
314 Nincada
315 Ninjask
316 Shedinja
317 Whismur
318 Loudred
319 Exploud
320 Makuhita
321 Hariyama
322 Azurill
323 Nosepass
324 Skitty
325 Delcatty
326 Sableye
327 SableyeMega Sableye
328 Mawile
329 MawileMega Mawile
330 Aron
331 Lairon
332 Aggron
333 AggronMega Aggron
334 Meditite
335 Medicham
336 MedichamMega Medicham
337 Electrike
338 Manectric
339 ManectricMega Manectric
340 Plusle
341 Minun
342 Volbeat
343 Illumise
344 Roselia
345 Gulpin
346 Swalot
347 Carvanha
348 Sharpedo
349 SharpedoMega Sharpedo
350 Wailmer
351 Wailord
352 Numel
353 Camerupt
354 CameruptMega Camerupt
355 Torkoal
356 Spoink
357 Grumpig
358 Spinda
359 Trapinch
360 Vibrava
361 Flygon
362 Cacnea
363 Cacturne
364 Swablu
365 Altaria
366 AltariaMega Altaria
367 Zangoose
368 Seviper
369 Lunatone
370 Solrock
371 Barboach
372 Whiscash
373 Corphish
374 Crawdaunt
375 Baltoy
376 Claydol
377 Lileep
378 Cradily
379 Anorith
380 Armaldo
381 Feebas
382 Milotic
383 Castform
384 Kecleon
385 Shuppet
386 Banette
387 BanetteMega Banette
388 Duskull
389 Dusclops
390 Tropius
391 Chimecho
392 Absol
393 AbsolMega Absol
394 Wynaut
395 Snorunt
396 Glalie
397 GlalieMega Glalie
398 Spheal
399 Sealeo
400 Walrein
401 Clamperl
402 Huntail
403 Gorebyss
404 Relicanth
405 Luvdisc
406 Bagon
407 Shelgon
408 Salamence
409 SalamenceMega Salamence
410 Beldum
411 Metang
412 Metagross
413 MetagrossMega Metagross
414 Regirock
415 Regice
416 Registeel
417 Latias
418 LatiasMega Latias
419 Latios
420 LatiosMega Latios
421 Kyogre
422 KyogrePrimal Kyogre
423 Groudon
424 GroudonPrimal Groudon
425 Rayquaza
426 RayquazaMega Rayquaza
427 Jirachi
428 DeoxysNormal Forme
429 DeoxysAttack Forme
430 DeoxysDefense Forme
431 DeoxysSpeed Forme
432 Turtwig
433 Grotle
434 Torterra
435 Chimchar
436 Monferno
437 Infernape
438 Piplup
439 Prinplup
440 Empoleon
441 Starly
442 Staravia
443 Staraptor
444 Bidoof
445 Bibarel
446 Kricketot
447 Kricketune
448 Shinx
449 Luxio
450 Luxray
451 Budew
452 Roserade
453 Cranidos
454 Rampardos
455 Shieldon
456 Bastiodon
457 Burmy
458 WormadamPlant Cloak
459 WormadamSandy Cloak
460 WormadamTrash Cloak
461 Mothim
462 Combee
463 Vespiquen
464 Pachirisu
465 Buizel
466 Floatzel
467 Cherubi
468 Cherrim
469 Shellos
470 Gastrodon
471 Ambipom
472 Drifloon
473 Drifblim
474 Buneary
475 Lopunny
476 LopunnyMega Lopunny
477 Mismagius
478 Honchkrow
479 Glameow
480 Purugly
481 Chingling
482 Stunky
483 Skuntank
484 Bronzor
485 Bronzong
486 Bonsly
487 Mime Jr.
488 Happiny
489 Chatot
490 Spiritomb
491 Gible
492 Gabite
493 Garchomp
494 GarchompMega Garchomp
495 Munchlax
496 Riolu
497 Lucario
498 LucarioMega Lucario
499 Hippopotas
500 Hippowdon
501 Skorupi
502 Drapion
503 Croagunk
504 Toxicroak
505 Carnivine
506 Finneon
507 Lumineon
508 Mantyke
509 Snover
510 Abomasnow
511 AbomasnowMega Abomasnow
512 Weavile
513 Magnezone
514 Lickilicky
515 Rhyperior
516 Tangrowth
517 Electivire
518 Magmortar
519 Togekiss
520 Yanmega
521 Leafeon
522 Glaceon
523 Gliscor
524 Mamoswine
525 Porygon-Z
526 Gallade
527 GalladeMega Gallade
528 Probopass
529 Dusknoir
530 Froslass
531 Rotom
532 RotomHeat Rotom
533 RotomWash Rotom
534 RotomFrost Rotom
535 RotomFan Rotom
536 RotomMow Rotom
537 Uxie
538 Mesprit
539 Azelf
540 Dialga
541 Palkia
542 Heatran
543 Regigigas
544 GiratinaAltered Forme
545 GiratinaOrigin Forme
546 Cresselia
547 Phione
548 Manaphy
549 Darkrai
550 ShayminLand Forme
551 ShayminSky Forme
552 Arceus
553 Victini
554 Snivy
555 Servine
556 Serperior
557 Tepig
558 Pignite
559 Emboar
560 Oshawott
561 Dewott
562 Samurott
563 Patrat
564 Watchog
565 Lillipup
566 Herdier
567 Stoutland
568 Purrloin
569 Liepard
570 Pansage
571 Simisage
572 Pansear
573 Simisear
574 Panpour
575 Simipour
576 Munna
577 Musharna
578 Pidove
579 Tranquill
580 Unfezant
581 Blitzle
582 Zebstrika
583 Roggenrola
584 Boldore
585 Gigalith
586 Woobat
587 Swoobat
588 Drilbur
589 Excadrill
590 Audino
591 AudinoMega Audino
592 Timburr
593 Gurdurr
594 Conkeldurr
595 Tympole
596 Palpitoad
597 Seismitoad
598 Throh
599 Sawk
600 Sewaddle
601 Swadloon
602 Leavanny
603 Venipede
604 Whirlipede
605 Scolipede
606 Cottonee
607 Whimsicott
608 Petilil
609 Lilligant
610 Basculin
611 Sandile
612 Krokorok
613 Krookodile
614 Darumaka
615 DarmanitanStandard Mode
616 DarmanitanZen Mode
617 Maractus
618 Dwebble
619 Crustle
620 Scraggy
621 Scrafty
622 Sigilyph
623 Yamask
624 Cofagrigus
625 Tirtouga
626 Carracosta
627 Archen
628 Archeops
629 Trubbish
630 Garbodor
631 Zorua
632 Zoroark
633 Minccino
634 Cinccino
635 Gothita
636 Gothorita
637 Gothitelle
638 Solosis
639 Duosion
640 Reuniclus
641 Ducklett
642 Swanna
643 Vanillite
644 Vanillish
645 Vanilluxe
646 Deerling
647 Sawsbuck
648 Emolga
649 Karrablast
650 Escavalier
651 Foongus
652 Amoonguss
653 Frillish
654 Jellicent
655 Alomomola
656 Joltik
657 Galvantula
658 Ferroseed
659 Ferrothorn
660 Klink
661 Klang
662 Klinklang
663 Tynamo
664 Eelektrik
665 Eelektross
666 Elgyem
667 Beheeyem
668 Litwick
669 Lampent
670 Chandelure
671 Axew
672 Fraxure
673 Haxorus
674 Cubchoo
675 Beartic
676 Cryogonal
677 Shelmet
678 Accelgor
679 Stunfisk
680 Mienfoo
681 Mienshao
682 Druddigon
683 Golett
684 Golurk
685 Pawniard
686 Bisharp
687 Bouffalant
688 Rufflet
689 Braviary
690 Vullaby
691 Mandibuzz
692 Heatmor
693 Durant
694 Deino
695 Zweilous
696 Hydreigon
697 Larvesta
698 Volcarona
699 Cobalion
700 Terrakion
701 Virizion
702 TornadusIncarnate Forme
703 TornadusTherian Forme
704 ThundurusIncarnate Forme
705 ThundurusTherian Forme
706 Reshiram
707 Zekrom
708 LandorusIncarnate Forme
709 LandorusTherian Forme
710 Kyurem
711 KyuremBlack Kyurem
712 KyuremWhite Kyurem
713 KeldeoOrdinary Forme
714 KeldeoResolute Forme
715 MeloettaAria Forme
716 MeloettaPirouette Forme
717 Genesect
718 Chespin
719 Quilladin
720 Chesnaught
721 Fennekin
722 Braixen
723 Delphox
724 Froakie
725 Frogadier
726 Greninja
727 Bunnelby
728 Diggersby
729 Fletchling
730 Fletchinder
731 Talonflame
732 Scatterbug
733 Spewpa
734 Vivillon
735 Litleo
736 Pyroar
737 FlabÃ©bÃ©
738 Floette
739 Florges
740 Skiddo
741 Gogoat
742 Pancham
743 Pangoro
744 Furfrou
745 Espurr
746 MeowsticMale
747 MeowsticFemale
748 Honedge
749 Doublade
750 AegislashBlade Forme
751 AegislashShield Forme
752 Spritzee
753 Aromatisse
754 Swirlix
755 Slurpuff
756 Inkay
757 Malamar
758 Binacle
759 Barbaracle
760 Skrelp
761 Dragalge
762 Clauncher
763 Clawitzer
764 Helioptile
765 Heliolisk
766 Tyrunt
767 Tyrantrum
768 Amaura
769 Aurorus
770 Sylveon
771 Hawlucha
772 Dedenne
773 Carbink
774 Goomy
775 Sliggoo
776 Goodra
777 Klefki
778 Phantump
779 Trevenant
780 PumpkabooAverage Size
781 PumpkabooSmall Size
782 PumpkabooLarge Size
783 PumpkabooSuper Size
784 GourgeistAverage Size
785 GourgeistSmall Size
786 GourgeistLarge Size
787 GourgeistSuper Size
788 Bergmite
789 Avalugg
790 Noibat
791 Noivern
792 Xerneas
793 Yveltal
794 Zygarde50% Forme
795 Diancie
796 DiancieMega Diancie
797 HoopaHoopa Confined
798 HoopaHoopa Unbound
799 Volcanion

# FILTER

In [ ]:
Filter1 = print(Data2.loc[Data2["Speed"]>70])

       #                       Name   Type 1  Type 2   HP  Attack  Defense  \
2      3                   Venusaur    Grass  Poison   80      82       83
3      3      VenusaurMega Venusaur    Grass  Poison   80     100      123
5      5                 Charmeleon     Fire     NaN   58      64       58
6      6                  Charizard     Fire  Flying   78      84       78
7      6  CharizardMega Charizard X     Fire  Dragon   78     130      111
..   ...                        ...      ...     ...  ...     ...      ...
792  716                    Xerneas    Fairy     NaN  126     131       95
793  717                    Yveltal     Dark  Flying  126     131       95
794  718           Zygarde50% Forme   Dragon  Ground  108     100      121
796  719        DiancieMega Diancie     Rock   Fairy   50     160      110
798  720         HoopaHoopa Unbound  Psychic    Dark   80     160       60

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
2        100      100     80           1      False
3        122      120     80           1      False
5         80       65     80           1      False
6        109       85    100           1      False
7        130       85    100           1      False
..       ...      ...    ...         ...        ...
792      131       98     99           6       True
793      131       98     99           6       True
794       81       95     95           6       True
796      160      110    110           6       True
798      170      130     80           6       True

[337 rows x 12 columns]

In [ ]:
print(Filter1)

None

In [ ]:
#fILTER Type two -

In [ ]:
Filter2 = print(Data2.loc[Data2["Type 2"]=="Poison"])

       #                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65
1      2                Ivysaur  Grass  Poison   60      62       63       80
2      3               Venusaur  Grass  Poison   80      82       83      100
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122
16    13                 Weedle    Bug  Poison   40      35       30       20
17    14                 Kakuna    Bug  Poison   45      25       50       25
18    15               Beedrill    Bug  Poison   65      90       40       45
19    15  BeedrillMega Beedrill    Bug  Poison   65     150       40       15
48    43                 Oddish  Grass  Poison   45      50       55       75
49    44                  Gloom  Grass  Poison   60      65       70       85
50    45              Vileplume  Grass  Poison   75      80       85      110
53    48                Venonat    Bug  Poison   60      55       50       40
54    49               Venomoth    Bug  Poison   70      65       60       90
75    69             Bellsprout  Grass  Poison   50      75       35       70
76    70             Weepinbell  Grass  Poison   65      90       50       85
77    71             Victreebel  Grass  Poison   80     105       65      100
78    72              Tentacool  Water  Poison   40      40       35       50
79    73             Tentacruel  Water  Poison   80      70       65       80
99    92                 Gastly  Ghost  Poison   30      35       30      100
100   93                Haunter  Ghost  Poison   45      50       45      115
101   94                 Gengar  Ghost  Poison   60      65       60      130
102   94      GengarMega Gengar  Ghost  Poison   60      65       80      170
181  167               Spinarak    Bug  Poison   40      60       40       40
182  168                Ariados    Bug  Poison   70      90       70       60
227  211               Qwilfish  Water  Poison   65      95       75       55
292  269                 Dustox    Bug  Poison   60      50       70       50
344  315                Roselia  Grass  Poison   50      60       45      100
451  406                  Budew  Grass  Poison   40      30       35       50
452  407               Roserade  Grass  Poison   60      70       65      125
603  543               Venipede    Bug  Poison   30      45       59       30
604  544             Whirlipede    Bug  Poison   40      55       99       40
605  545              Scolipede    Bug  Poison   60     100       89       55
651  590                Foongus  Grass  Poison   69      55       45       55
652  591              Amoonguss  Grass  Poison  114      85       70       85

     Sp. Def  Speed  Generation  Legendary
0         65     45           1      False
1         80     60           1      False
2        100     80           1      False
3        120     80           1      False
16        20     50           1      False
17        25     35           1      False
18        80     75           1      False
19        80    145           1      False
48        65     30           1      False
49        75     40           1      False
50        90     50           1      False
53        55     45           1      False
54        75     90           1      False
75        30     40           1      False
76        45     55           1      False
77        70     70           1      False
78       100     70           1      False
79       120    100           1      False
99        35     80           1      False
100       55     95           1      False
101       75    110           1      False
102       95    130           1      False
181       40     30           2      False
182       60     40           2      False
227       55     85           2      False
292       90     65           3      False
344       80     65           3      False
451       70     55           4      False
452      105     90           4      False
603       39     57           5      False
604       79     47           5      False
605       69    112           5      False
651       55     15           5      False
652       80     30           5      False

In [ ]:
print(Filter2)

None

In [ ]:
print(Data1.ndim)

2

# SORTING DATA

In [ ]:
#sort data in desending order w.e.r to "HP"

In [ ]:
Data2.sort_values(["HP"],ascending=False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
261,242,Blissey,Normal,NaN,255,10,10,75,135,55,2,False
121,113,Chansey,Normal,NaN,250,5,5,35,105,50,1,False
217,202,Wobbuffet,Psychic,NaN,190,33,58,33,58,33,2,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False
388,355,Duskull,Ghost,NaN,20,40,90,30,90,25,3,False
55,50,Diglett,Ground,NaN,10,55,25,35,45,95,1,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

# EDIT DATA

In [ ]:
Data2["Power"] = Data2["HP"] + Data2["Attack"]
print(Data2.head())

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary  Power
0       65     45           1      False     94
1       80     60           1      False    122
2      100     80           1      False    162
3      120     80           1      False    180
4       50     65           1      False     91

In [ ]:
Data2

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Power
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,94
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,122
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,162
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,180
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,150
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,210
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,190
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,240
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,190

In [ ]:
Data2 = Data2.drop(columns=["Power"])

In [ ]:
Data2

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# EXPORT CSV

In [ ]:
Data2.to_csv("C:\\Users\\dhirendra.p_embibe\\Desktop\\\dataset.csv")  #EXPORT THE FILERED DATA

# Checking Null values

In [ ]:
Data2.isna().any() #CHECK entire data if there is any NaN/Null/Blank columns value

#             False
Name          False
Type 1        False
Type 2        False
HP            False
Attack        False
Defense       False
Sp. Atk       False
Sp. Def       False
Speed         False
Generation    False
Legendary     False
dtype: bool

# removing The Null Values

In [ ]:
Data2 = Data2[Data2["Type 2"].notna()]

In [ ]:
Data2.isna().any() #CHECK entire data if there is any NaN/Null/Blank columns value

#             False
Name          False
Type 1        False
Type 2        False
HP            False
Attack        False
Defense       False
Sp. Atk       False
Sp. Def       False
Speed         False
Generation    False
Legendary     False
dtype: bool

# Replacin the NULL values with Data (Mean of that coulumn)

In [ ]:
FillMean = Data2["Speed"].fillna(Data2["Speed"].mean())

In [ ]:
FillMean

0       45
1       60
2       80
3       80
6      100
      ...
795     50
796    110
797     70
798     80
799     70
Name: Speed, Length: 414, dtype: int64

In [ ]:
print(Data2)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
6      6              Charizard     Fire  Flying  78      84       78
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
6        109       85    100           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[414 rows x 12 columns]

# Replace number 1(Integer) with Name(String) one in Generation coloumn

In [ ]:
print(Data2.head())

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
6  6              Charizard   Fire  Flying  78      84       78      109

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
6       85    100           1      False

In [ ]:
Generationconv =  set(Data2['Generation'])

In [ ]:
Data2['Generation'] = Data2['Generation'].map({1:"one", 2: "two", 3:"three", 4:"four", 5:"five", 6:"six"}).astype(str)
print(Data2.head())

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
6  6              Charizard   Fire  Flying  78      84       78      109

   Sp. Def  Speed Generation  Legendary
0       65     45        one      False
1       80     60        one      False
2      100     80        one      False
3      120     80        one      False
6       85    100        one      False

C:\Users\DHIREN~1.P_E\AppData\Local\Temp/ipykernel_4940/4036325375.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data2['Generation'] = Data2['Generation'].map({1:"one", 2: "two", 3:"three", 4:"four", 5:"five", 6:"six"}).astype(str)